// Auto-generated – lists PDF files per publication year.
var LITERATURE = {
  "2026": [
    "Contributions of sele_Bera S_Liu L_Ma W_Xu Z_Cancer causes and control - CCC_2026.pdf",
    "Expression Analysis, Di_Nair AS_Sujir N_Sen D_A_International dental journal_2026.pdf",
    "Gene regulatory net_Ray U_Singh A_Saman_NPJ systems biology and applications_2026.pdf"
  ],
  "2025": [
    "An Automated Appr_Madhura MG_Vijaya_Asian Pacific journal of cancer preventi_2025.pdf",
    "An Integrative Bi_Bhola N_Jaiswal A_International journal of molecular scien_2025.pdf",
    "Antisense RNAs (a_Rajput M_Dixit R__Gastroenterology and hepatology from bed_2025.pdf",
    "Aurora Kinase A inhibitor al_Thakur D_Sengupta D_Kar S_Cha_Discover oncology_2025.pdf",
    "CACYBP expression predicts progno_Odat RM_Yasin JA_Hussein AM_Qtais_Medicine_2025.pdf",
    "Chemotherapy-induced alter_Ranmale S_Kumar P_Tongaonka_Frontiers in oncology_2025.pdf",
    "Clinical data inves_Raut R_Srivastava D__Biochemistry and biophysics reports_2025.pdf",
    "Diagnostic value of cir_Ikram F_Mathur P_Dubey_The journal of liquid biopsy_2025.pdf",
    "Differential Expression of miR_Moiz S_Saha B_Mondal V_Bishnu_Non-coding RNA_2025.pdf",
    "Dysregulated miRNA Expression and_Shuaib M_Saini D_Sharma G_Singh I__Cancers_2025.pdf",
    "Establishing molecular bioma_Gupta K_Raval I_Puvar A_Shai_Scientific reports_2025.pdf",
    "Excessive Urinary p75ecd_Dhasmana S_Dhasmana A_Kha_Current neuropharmacology_2025.pdf",
    "Exploring Breast Cancer-_Charu Meena H_Sagaya Jan_Archives of Razi Institute_2025.pdf",
    "Expression and characterizat_Yoshitha KL_Ingole SD_Bharuc_Scientific reports_2025.pdf",
    "Expression of DKK1, HOXC6, and YKT_Haldar U_Gopal N_Prathipati K_Balk_Cureus_2025.pdf",
    "Expression profile_Sharma D_Gupta S_K_The Indian journal of medical research_2025.pdf",
    "Functional characterization_Sharma M_Chourasia N_Priyank_Scientific reports_2025.pdf",
    "Human papilloma virus infect_Hamid S_Khan MS_Khan MA_Muham_Discover oncology_2025.pdf",
    "Identification and vali_Oli M MK_Syed Masood JAI_Frontiers in bioinformatics_2025.pdf",
    "Identification of a_Choudhury S_Bararia_European journal of medical research_2025.pdf",
    "Influences of aqua-(2-formyl_Singh V_Singh R_Goswami P_Ma_Scientific reports_2025.pdf",
    "Integrated profiling reveals_Ghose S_Chaudry UR_Chakravar_Scientific reports_2025.pdf",
    "Integrative analysis identif_Raut R_Srivastava D_Chakrabor_Discover oncology_2025.pdf",
    "Investigating the Role_Sulaimani MN_Singh P_S_Cancer genomics and proteomics_2025.pdf",
    "Metal ion transporter SL_Chiang YC_Wang CY_Kumar S_Cancer cell international_2025.pdf",
    "Microbial signatu_Kavitha L_Kuzhalm_Journal of applied oral science - revist_2025.pdf",
    "Molecular analysis of HPV16 a_Hussain SFJ_Abullais SS_Bottu_Oncology letters_2025.pdf",
    "Multi-omics and AI-driven im_Vasudevan K_T D_Hebbar SR_Se_Scientific reports_2025.pdf",
    "Multi-omics insights into_Loganathan T_Doss CGP_Frontiers in medicine_2025.pdf",
    "Predicting the hub interacto_Yadalam PK_Arumuganainar D_N_Scientific reports_2025.pdf",
    "Systems biology-driven ident_Anbarasu S_Balaji S_Ramaiah S_Discover oncology_2025.pdf",
    "TMPO-AS1-hsa-let-_Vats P_Baweja B_N_Reports of practical oncology and radiot_2025.pdf",
    "Tumor Suppressor_Unnikrishnan K_Kr_Asian Pacific journal of cancer preventi_2025.pdf",
    "Urine exosome bio_Vijay B_Devkumar_Journal of Ayurveda and integrative medi_2025.pdf"
  ],
  "2024": [
    "A novel ITGB8 transcrip_Narayanan A_More AS_Talr_Journal of ovarian research_2024.pdf",
    "CmirC update 2024 -_Ware AP_Satyamoorthy_Functional and integrative genomics_2024.pdf",
    "Cuproptosis, the n_Zhao R_Sukocheva O_Cell communication and signaling - CCS_2024.pdf",
    "Deciphering the miRNA-mRNA Inter_Balasundaram A_Mitra TS_Tayubi IA_ACS omega_2024.pdf",
    "Delineating the role of nucl_Manickasamy MK_Jayaprakash S__Discover oncology_2024.pdf",
    "Differential Expr_Patnam S_Majumder_ACS pharmacology and translational scien_2024.pdf",
    "Elucidating the Role of MicroRNA-1_Nair MG_Mavatkar AD_Naidu CM_V P S__Cells_2024.pdf",
    "ExplORRNet - An interacti_Lawarde A_Sharif Rahmani E_Non-coding RNA research_2024.pdf",
    "Expression profili_Kushwaha S_Yadav R_The Indian journal of medical research_2024.pdf",
    "Grain iron and zinc content_Gogoi S_Singh S_Swamy BPM_Da_Scientific reports_2024.pdf",
    "Immune-Related Long Non-Codi_Uttam V_Kapoor HS_Rana MK_Ya_Cancer informatics_2024.pdf",
    "Integrating network_Khurshid S_Usmani S__Frontiers in molecular biosciences_2024.pdf",
    "Is cross-species hor_Rajput M_Pandey M_Di_World journal of surgical oncology_2024.pdf",
    "LncRNAs in oncoge_Roy D_Bhattachary_Frontiers in cell and developmental biol_2024.pdf",
    "Novel lncRNAs LINC01221,_Sharma P_Kaur P_Bhatia P__Cancer cell international_2024.pdf",
    "Pan-cancer analys_Huang L_Irshad S__American journal of translational resear_2024.pdf",
    "Pan-cancer explorati_Shenoy US_Basavaraja_Clinical and experimental medicine_2024.pdf",
    "Protocol for identifying key g_Agrawal P_Hannenhalli S_STAR protocols_2024.pdf",
    "The regulation of plasm_Manzoor HB_Asare-Werehen_Journal of ovarian research_2024.pdf",
    "Unveiling FRG1's DNA repair_Shubhanjali S_Mohapatra T_Kh_Scientific reports_2024.pdf",
    "Unveiling the cytotoxic and ant_Gupta P_Singh S_Rai N_Verma A_T_RSC advances_2024.pdf",
    "Uracil as a biomarker for sp_Shaikh S_Basu S_Bag S_Chatte_Scientific reports_2024.pdf"
  ],
  "2023": [
    "A Comprehensive S_Bhatiya M_Pathak_Archivum immunologiae et therapiae exper_2023.pdf",
    "A systemic analysis of mo_Chatterjee P_Bhowmik D_Roy_Channels (Austin, Tex.)_2023.pdf",
    "Alternatively Spliced_Althenayyan S_AlMuhan_Journal of personalized medicine_2023.pdf",
    "C1QA and COMP - plasma-based_Gorai PK_Bharti PS_Kumar S_R_Scientific reports_2023.pdf",
    "CESCProg - a compact prognostic mo_Muthamilselvan S_Palaniappan A_PeerJ_2023.pdf",
    "Cell State Transi_Richard V_Nair MG_International journal of molecular scien_2023.pdf",
    "Differential Expression of Non-Cod_Mishra A_Kumar R_Mishra SN_Vijayara_Cells_2023.pdf",
    "Differential expr_Awasthi S_Ahmad S_International journal of health sciences_2023.pdf",
    "Directional preference fo_Khan S_Khan MWA_Sherwani S_Frontiers in immunology_2023.pdf",
    "Expression of CD44 in Hea_Kavitha L_Vijayashree Priy_Global medical genetics_2023.pdf",
    "Expression profil_Ulaganathan K_Pura_Journal of cancer research and clinical_2023.pdf",
    "GPR56 signaling p_Ganesh RA_Venkata_Journal of cell communication and signal_2023.pdf",
    "Identification of BRCA1-2_Elias K_Smyczynska U_Stawis_Nature communications_2023.pdf",
    "Integrative Analy_T B B_A JM_K B H__Asian Pacific journal of cancer preventi_2023.pdf",
    "Network-Derived Radioresistant_Sivakumar M_Ahmad SF_Emran TB_A_Marine drugs_2023.pdf",
    "TRPA1 activation and Hsp90 inh_Radhakrishnan A_Mukherjee T_Ma_BMC immunology_2023.pdf",
    "Whole transcriptome sequen_Desai SS_Ravindran F_Pancha_Frontiers in genetics_2023.pdf"
  ],
  "2022": [
    "2D-DIGE-Based Proteomic Pro_Sivagnanam A_Shyamsundar V_K_Journal of oncology_2022.pdf",
    "A Comprehensive C_Jothimani G_Patha_Tissue engineering and regenerative medi_2022.pdf",
    "Curcumin alters distin_Nirgude S_Desai S_Chou_Cancer reports (Hoboken, N.J.)_2022.pdf",
    "DEGnext - classification of_Kakati T_Bhattacharyya DK_Ka_BMC bioinformatics_2022.pdf",
    "Delineating the E_Banerjee M_Al-Ery_Toxicological sciences - an official jou_2022.pdf",
    "Differential Expr_Ukey S_Ramteke A__Asian Pacific journal of cancer preventi_2022.pdf",
    "Differential Expression of_Hegde M_Daimary UD_Jose S_S_Frontiers in genetics_2022.pdf",
    "Differential Expression_Das S_Rai A_Rai SN_Entropy (Basel, Switzerland)_2022.pdf",
    "Exosomal microRNAs Target_Jayaseelan VP_Arumugam P_Global medical genetics_2022.pdf",
    "Green-Based Approach to Synthesi_Gupta P_Rai N_Verma A_Saikia D_Si_ACS omega_2022.pdf",
    "Human telomerase reverse transcri_Prasad RR_Mishra DK_Kumar M_Yadava_Heliyon_2022.pdf",
    "Importance of Extracellul_Datta B_Paul D_Dey T_Pal S_ACS bio and med chem Au_2022.pdf",
    "In-silico discovery of dual activ_Raja A_Shekhar N_Singh H_Prakash_PloS one_2022.pdf",
    "Integrated proteo_George IA_Sathe G_Frontiers in cell and developmental biol_2022.pdf",
    "Machine learning_Thalor A_Kumar Jo_Computational and structural biotechnolo_2022.pdf",
    "Metabolic Pathways, Enzymes, and_Kumar R_Mishra A_Gautam P_Feroz Z__Cancers_2022.pdf",
    "Pharmacological a_Shabna A_Antony J_Cellular and molecular life sciences - C_2022.pdf",
    "Quantitative Prot_T A S_Narayan M_K_Asian Pacific journal of cancer preventi_2022.pdf",
    "Tumor-associated macroph_Radharani NNV_Yadav AS_Ni_Cancer cell international_2022.pdf",
    "Unraveling unique_Fathima S_Sinha S_Computational and structural biotechnolo_2022.pdf",
    "_Mukherjee S_Kar A_Paul P_Dey S_Bis_Frontiers in cell and developmental biol_2022.pdf",
    "miR-15a and miR-15b mod_Pathania AS_Prathipati_Molecular therapy oncolytics_2022.pdf"
  ],
  "2021": [
    "A Comprehensive Survey of Statisti_Das S_Rai A_Merchant ML_Cave MC_Rai_Genes_2021.pdf",
    "A genome-wide expression pro_Sharma H_Niveditha D_Chowdhur_Discover oncology_2021.pdf",
    "Analysis of H3K4me3-ChIP-_Kotipalli A_Banerjee R_Ka_Genomics and informatics_2021.pdf",
    "Analysis of immun_Chakraborty P_Che_Computational and structural biotechnolo_2021.pdf",
    "Comprehensive overview o_Rana R_Sharma S_Ganguly N_Molecular biology reports_2021.pdf",
    "Deciphering the g_Aparna J_Smiline-_Molecular biology research communication_2021.pdf",
    "Diagnostic and Prognost_Lal M_Ansari AH_Agrawal_Journal of clinical medicine_2021.pdf",
    "Differential expres_Zhang Y_Qazi S_Raza_Saudi journal of biological sciences_2021.pdf",
    "Dynamic alteration in miRN_Banerjee M_Ferragut Cardos_Archives of toxicology_2021.pdf",
    "Endogenous, tissue-resi_Bhartiya D_Patel H_Kaush_Journal of ovarian research_2021.pdf",
    "Exploring the Differential_Patra R_Das NC_Mukherjee S_Frontiers in genetics_2021.pdf",
    "Exposures to 2,4-_Kaur G_Kumar BVS__Journal of occupational medicine and tox_2021.pdf",
    "GeneCloudOmics - A Data_Helmy M_Agrawal R_Ali J__Frontiers in bioinformatics_2021.pdf",
    "High expression o_Nair MG_Prabhu JS_Cancer treatment and research communicat_2021.pdf",
    "LncRNA Hmrhl regulates expressio_Choudhury SR_Dutta S_Bhaduri U_R_NAR cancer_2021.pdf",
    "Malignant Pleural Mesothelioma In_Karunakaran KB_Yanamala N_Boyce G__Cancers_2021.pdf",
    "Molecular Subtype_Li S_Mai Z_Gu W_O_Frontiers in cell and developmental biol_2021.pdf",
    "Orai3 Regulates Pancreatic Cancer_Arora S_Tanwar J_Sharma N_Saurav S_Cancers_2021.pdf",
    "Prognostic biomarkers for predict_Arora C_Kaur D_Naorem LD_Raghava_PloS one_2021.pdf",
    "Proteomic Signatures of Diffuse a_Singh S_Bhat MY_Sathe G_Gopal C_Sh_Cancers_2021.pdf",
    "Smell Detection Agent Optimisat_Sivan SL_Sukumara Pillai VCS_Biomolecules_2021.pdf",
    "Statistical Approach of_Das S_Rai SN_Entropy (Basel, Switzerland)_2021.pdf",
    "Statistical methods for analysis_Das S_Rai SN_MethodsX_2021.pdf",
    "SwarnSeq - An improved statistica_Das S_Rai SN_Genomics_2021.pdf",
    "Systematic analysis of migra_Pal J_Becker AC_Dhamija S_Se_Molecular oncology_2021.pdf",
    "Targeting Farnesoid X rece_Girisa S_Henamayee S_Parama_Molecular biomedicine_2021.pdf",
    "To study the role of p_Barik S_Mitra S_Suryav_Cancer reports (Hoboken, N.J.)_2021.pdf",
    "Transcriptome profiling by c_Maurya NS_Kushwaha S_Chawade_Scientific reports_2021.pdf",
    "Transcriptomic Biomarkers for Tube_de Araujo LS_Ribeiro-Alves M_Wipper_Cells_2021.pdf",
    "Transcriptomic landscape of_Singh MP_Rai S_Singh NK_Sriv_Scientific reports_2021.pdf",
    "Unsupervised subtyping and methyl_Roy S_Singh AP_Gupta D_Heliyon_2021.pdf"
  ],
  "2020": [
    "A Linear Regression and Deep Learn_Mallik S_Seth S_Bhadra T_Zhao Z_Genes_2020.pdf",
    "Aberrant promoter_Kadian LK_Gulshan_American journal of translational resear_2020.pdf",
    "Artificial Intelligence_Patel SK_George B_Rai V_Frontiers in pharmacology_2020.pdf",
    "Claudin-1, A Doub_Bhat AA_Syed N_Th_International journal of molecular scien_2020.pdf",
    "Clinical relevance_Singh L_Singh MK_R_Cancer immunology, immunotherapy - CII_2020.pdf",
    "Construction of the gene reg_Srikanth S_Ramachandran S_Mo_Scientific reports_2020.pdf",
    "Defective Proventriculus_Mehrotra S_Bansal P_Oli N__Frontiers in physiology_2020.pdf",
    "Differential Expr_Karri RL_Subraman_Journal of microscopy and ultrastructure_2020.pdf",
    "Identification and differ_Barik SK_Mohanty KK_Mohant_BMC infectious diseases_2020.pdf"
  ],
  "2019": [
    "Data on solute carrier transpo_Barat A_Sahoo PK_Kumar R_Goel C_Data in brief_2019.pdf",
    "Differential Expression Prof_Sharma N_Saxena S_Agrawal I__Scientific reports_2019.pdf",
    "Differential expr_Singh MK_Singh L_C_Journal of cancer research and clinical_2019.pdf",
    "Differential expression of Helio_Adil AAM_Bommanabonia AK_Vaithy A_3 Biotech_2019.pdf",
    "Downregulation of_Harishankar MK_Mo_Brazilian journal of otorhinolaryngology_2019.pdf",
    "Gene Ontology and_Hasan MN_Razvi SS_Analytical cellular pathology (Amsterdam_2019.pdf",
    "Immunohistochemical Identificat_Rao VV_Mohanty A_Bio-protocol_2019.pdf",
    "MicroRNAs as Key Regulators of_Satapathy S_Kumar C_Singh RK_Cell medicine_2019.pdf",
    "Novel significant stage-specific_Sarathi A_Palaniappan A_BMC cancer_2019.pdf",
    "Prognostic and Clinicopathologica_Mongre RK_Jung S_Mishra CB_Lee BS__Cancers_2019.pdf",
    "Risk of cognition_Anusa AM_Thavaraj_Journal of oral biology and craniofacial_2019.pdf"
  ],
  "2018": [
    "A model species for agricult_Schoville SD_Chen YH_Anderss_Scientific reports_2018.pdf",
    "AIRE promotes androgen-independ_Kalra R_Bhagyaraj E_Tiwari D_Nan_Oncogenesis_2018.pdf",
    "Analysis of MicroRNA-mRNA In_Richard V_Raju R_Paul AM_Giri_Oncology research_2018.pdf",
    "Constitutive activation and over_Gupta S_Kumar P_Kaur H_Sharma N__Oncotarget_2018.pdf",
    "Delineating Potential_Shah HK_Bhat MA_Sharma_The open biochemistry journal_2018.pdf",
    "Differential Expr_Krishna A_Bhatt M_Asian Pacific journal of cancer preventi_2018.pdf",
    "Differential Expr_Shaheen S_Fawaz F_International journal of molecular scien_2018.pdf",
    "Differential expr_Kavyasudha C_Joel_Turkish journal of biology = Turk biyolo_2018.pdf",
    "Differential expression_Bharti R_Dey G_Das AK_Man_British journal of cancer_2018.pdf",
    "Differentially localiz_Pandey A_Tripathi SC_S_Cancer reports (Hoboken, N.J.)_2018.pdf",
    "Exosomal microRNA profiling to i_Panigrahi GK_Ramteke A_Birks D_A_Oncotarget_2018.pdf",
    "Expression analysi_Bharali D_Banerjee_The Indian journal of medical research_2018.pdf",
    "Impact of semaphorin_Butti R_Kumar TV_Nim_Breast cancer (Dove Medical Press)_2018.pdf",
    "The Origin and Functions o_Rajagopal C_Harikumar KB_Frontiers in oncology_2018.pdf",
    "The expression profile and progno_Hassan MK_Kumar D_Naik M_Dixit M_PloS one_2018.pdf",
    "Volatilomic insight of head_Taware R_Taunk K_Pereira JAM_Scientific reports_2018.pdf"
  ],
  "2017": [
    "A Stack-based Ens_Saha S_Mitra S_Yad_Genomics, proteomics and bioinformatics_2017.pdf",
    "An approach to forecast human ca_Salim A_Amjesh R_Chandra SS_BMC cancer_2017.pdf",
    "Cardamonin inhibits colonic_James S_Aparna JS_Paul AM_La_Scientific reports_2017.pdf",
    "Characterization of key trans_Verma G_Vishnoi K_Tyagi A_Jadl_Cancer medicine_2017.pdf",
    "Identification of Genetic an_Shilpi A_Bi Y_Jung S_Patra S_Cancer informatics_2017.pdf",
    "Immunohistochemical_Gangkak G_Bhattar R__Investigative and clinical urology_2017.pdf",
    "Proteomic identification of prote_Jaiswal RK_Kumar P_Sharma A_Mishr_PloS one_2017.pdf",
    "Sequence and Phyl_Ramsuran V_Hern\u00e1nd_Journal of immunology (Baltimore, Md. -_2017.pdf",
    "Src promotes castration-recurren_Chattopadhyay I_Wang J_Qin M_Gao_Oncotarget_2017.pdf"
  ],
  "2016": [
    "Abstracts from the 3rd Internat_Shay JW_Homma N_Zhou R_Naseer M_BMC genomics_2016.pdf",
    "Differential Expression of Stem C_Mishra DK_Veena U_Kaliki S_Kethir_PloS one_2016.pdf",
    "Differential alterations of_Ghatak S_Raha S_Genes and diseases_2016.pdf",
    "Differential expression of m_Sandhu V_Bowitz Lothe IM_Lab_Molecular oncology_2016.pdf",
    "Elucidation of molecular and_Naik RR_Gardi NL_Bapat SA_Scientific reports_2016.pdf",
    "Glucose transport -_Labak CM_Wang PY_Aro_American journal of cancer research_2016.pdf",
    "Increased expression of_Singh K_Agrawal NK_Gupta_International wound journal_2016.pdf",
    "Major Protein of_Nataraj SM_Prema_Journal of clinical and diagnostic resea_2016.pdf",
    "Molecular Understanding of Growth_Desai S_Srambikkal N_Yadav HD_She_PloS one_2016.pdf",
    "Oral squamous cell carcinoma_Manikandan M_Deva Magendhra R_Molecular cancer_2016.pdf"
  ],
  "2015": [
    "A knowledgebase r_Sharma J_Balakris_Journal of cell communication and signal_2015.pdf",
    "An Integrative Approach for Mappi_Sehgal M_Gupta R_Moussa A_Singh T_PloS one_2015.pdf",
    "Live detection and purificat_Kochurani KJ_Suganya AA_Nair_Scientific reports_2015.pdf",
    "Site-Specific MicroRNA Expression_Ranjha R_Aggarwal S_Bopanna S_Ahu_PloS one_2015.pdf",
    "Status of epigeneti_Singh V_Singh LC_Sin_American journal of cancer research_2015.pdf",
    "Studies on the role_Ashraf GM_Perveen A_Saudi journal of biological sciences_2015.pdf",
    "Survivin - A molec_Jaiswal PK_Goel A__The Indian journal of medical research_2015.pdf",
    "Transcriptomic analyses of gene_Ganguly P_Ganguly N_Virusdisease_2015.pdf"
  ],
  "2014": [
    "CCR9-CCL25 expression in non-sma_Gupta P_Sharma PK_Mir H_Singh R__Oncotarget_2014.pdf",
    "CSNK1A1 and Gli2 as Novel Ta_Mishra S_Cancer informatics_2014.pdf",
    "Differential expressio_Kazmi HR_Chandra A_Bagh_BioMed research international_2014.pdf",
    "Host response profile of hu_Sahu A_Kumar S_Sreenivasamur_Clinical proteomics_2014.pdf",
    "Potential therapeutic targets for_Bundela S_Sharma A_Bisen PS_PloS one_2014.pdf"
  ],
  "2013": [
    "Differential expression of HPV16_Mandal P_Bhattacharjee B_Das Ghos_PloS one_2013.pdf",
    "Influence of limo_Langeswaran K_Gow_Journal of natural science, biology, and_2013.pdf",
    "Over expression of minichromosome_Das M_Prasad SB_Yadav SS_Govardha_PloS one_2013.pdf",
    "Real-time PCR assay based on t_Kunder R_Jalali R_Sridhar E_Mo_Neuro-oncology_2013.pdf",
    "Regulation of protumorigenic_Sehgal P_Kumar N_Praveen Kuma_Molecular cancer_2013.pdf",
    "Syntrophin protei_Bhat HF_Adams ME__Cellular and molecular life sciences - C_2013.pdf"
  ],
  "2012": [
    "Acute exposure of apigenin induce_Singh P_Mishra SK_Noel S_Sharma S_PloS one_2012.pdf",
    "Molecular deregulation induce_Venkatesan N_Krishnakumar S_D_Molecular vision_2012.pdf"
  ],
  "2010": [
    "Development of the human cancer m_Bandyopadhyay S_Mitra R_Maulik U_Z_Silence_2010.pdf",
    "Identification of gene expr_Thakkar AD_Raj H_Chakrabart_Biomarkers in cancer_2010.pdf",
    "Silkworm thermal bio_Manjunatha HB_Rajesh_Journal of insect science (Online)_2010.pdf",
    "The differential expression o_Liang S_Singh M_Gam LH_Disease markers_2010.pdf"
  ],
  "2009": [
    "Molecular profiling to identi_Chattopadhyay I_Phukan R_Sing_Oncology reports_2009.pdf"
  ],
  "2008": [
    "A quantitative proteomi_Chaerkady R_Harsha HC_N_Journal of proteome research_2008.pdf",
    "Flow-cytometric monitoring of di_Chowdhury S_Bandyopadhyay S_Mand_BMC cancer_2008.pdf",
    "Involvement of TSC genes and dif_Chakraborty S_Mohiyuddin SM_Gopi_BMC cancer_2008.pdf"
  ],
  "2007": [
    "Differential expression and r_Kumar PS_Shiras A_Das G_Jagta_Molecular cancer_2007.pdf",
    "Over-expression of 14-3-3zeta is_Matta A_Bahadur S_Duggal R_Gupta_BMC cancer_2007.pdf"
  ],
  "2004": [
    "Molecular signatures of_Pillai AA_Bhattacharya RN_Journal of carcinogenesis_2004.pdf"
  ],
  "2003": [
    "Expression of biomarkers modu_Banerjee AG_Liu J_Yuan Y_Gopa_Molecular cancer_2003.pdf"
  ],
  "1998": [
    "Tumour-proliferat_Pillai MR_Jayaprak_Journal of cancer research and clinical_1998.pdf"
  ],
  "1996": [
    "Differential expr_Sujathan K_Kannan_Journal of cancer research and clinical_1996.pdf"
  ]
};
